### ISSUE TITLE
Add icon to the menurow

### ISSUE THREAD

**Issue by Namib** [manumaticx/Ti.DrawerLayout#14]
Hello,

I am trying to add an icon to the menurow along with the text. Can you help me achieve this?

**Comment by manumaticx** [comment]
Hi @Namib 

there are multiple ways to do this. 

If your code is based on [this demo](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App) then you might just want to use the [`leftImage`-property](http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.TableViewRow-property-leftImage) of Ti.UI.TableViewRow. Also have a look at this example:
[KitchenSink Layout 1](https://github.com/appcelerator/KitchenSink/blob/stable/Resources/ui/common/baseui/table_view_layout.js)

Or you can create your own row layouts according to this example:
[KitchenSink Layout 2](https://github.com/appcelerator/KitchenSink/blob/stable/Resources/ui/common/baseui/table_view_layout_2.js)

If your menu uses a ListView the you can use the [`image`-property](http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.ListItem-property-image) with the default layout. You can also create custom layouts, just have a look at the [ListView guide](http://docs.appcelerator.com/titanium/3.0/#!/guide/ListViews)

I hope this helps you. If you need further help I recommend you to [ask the community](http://developer.appcelerator.com/questions/newest) since this is not a DrawerLayout specific question.

**Comment by Namib** [comment]
Thanks a ton @manumaticx . I will try this, I'll make sure I ask such questions in community.

Thanks again for a quick reply :)

**Comment by Namib** [comment]
Can I change this menu dynamically? Please check my query on http://developer.appcelerator.com/question/181570/re-initialize-the-drawer-menu#answer-286710

I am trying to change the menu items based on user login/logout. A simple example would be a great help.


Thanks.

**Comment by manumaticx** [comment]
@Namib answered [there](http://developer.appcelerator.com/question/181570/re-initialize-the-drawer-menu#answer-286805)
