### ISSUE TITLE
Classic Version

### ISSUE THREAD

**Issue by DouglasHennrich** [manumaticx/Ti.DrawerLayout#20]
There's a way to use this module on Classic ?
Awesome work dude!

Thanks

**Comment by manumaticx** [comment]
Sure. Why not?

**Comment by DouglasHennrich** [comment]
What should I change to work on classic mode?

**Comment by manumaticx** [comment]
It's just the demo app in Alloy. There's nothing that should prevent you to use classic titanium.

Please have a look at:
- [the documentation](https://github.com/manumaticx/Ti.DrawerLayout/blob/master/documentation/index.md)
- [the example](https://github.com/manumaticx/Ti.DrawerLayout/blob/master/example/app.js)

Does this help?

**Comment by DouglasHennrich** [comment]
Thank you @manumaticx !

**Comment by DouglasHennrich** [comment]
There's another question... how should I do to make the centerView an "navigator window" ?

**Comment by manumaticx** [comment]
@DouglasHennrich can you explain in more detail?

**Comment by DouglasHennrich** [comment]
On the iOS version of this module I can make the centerView an NavigationWindow that allows me to navigate through .js files... how should I proceed to accomplish this on Android? Since Android don't support add a window inside another window ?

**Comment by manumaticx** [comment]
This module has no iOS version. It's poxying the native [DrawerLayout](http://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html). The NavigationWindow is an iOS-only component. You don't need this on Android. 

I've just add a new feature to this module which might be helpful to create such a thing (since lightweight windows don't work anymore) - you can replace the centerView of the drawer with:

```js
drawer.replaceCenterView(view, true);
```

Internally this will add your view to the android backstack (wrapped in a fragment). That means, you can go back to the previous view with the android back button.

Another solution would be just opening a new window (activity) You would need to go back (close the new window) to access the drawer then.

**Comment by manumaticx** [comment]
Btw. I've just activated gitter chat for this repo ;)

https://gitter.im/manumaticx/Ti.DrawerLayout

**Comment by manumaticx** [comment]
@DouglasHennrich Let me know if we can close this

**Comment by DouglasHennrich** [comment]
@manumaticx you can close it. Thanks my friend!
