### ISSUE TITLE
Closing secondWindow from menu?

### ISSUE THREAD

**Issue by Yakito** [manumaticx/Ti.DrawerLayout#34]
Hello, I am not sure this is an issue, but when I open the secondWindow the only way to get back seems to be with the back button. If I click on any element of the menu the title of the actionBar will change but the view stays visible (on top of the others?)

If anyone can share a workaround on how to close the SecondView when an element of the menu is clicks I will appreciate it.
Thanks!

**Comment by manumaticx** [comment]
@Yakito  How do you open this secondWindow? Do you mean replacing the centerView?
Can you maybe share some sample code? Thanks

**Comment by Yakito** [comment]
Hello Manuel, thanks for your time. I am using the Demo App https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App 

In order to open the SecondWindow I am using the following function

    function replaceCenterView(){
      var view = Alloy.createController('secondWindow').getView();
      // the second parameter tells the drawer to add this replacement to the backstack
      // so pressing the back-button brings the user back to the previous view
      // instead of closing the app
      Alloy.Globals.drawer.replaceCenterView(view, true);
    }

The problem with that is that when you are on it if you press the back button, it will work fine, but if you open the menu from it and you click on any element the SecondWindow will stay on top.

I am new with appcelerator so I am not very sure, I tried hiding the controller once the user click on a menu item from the SecondWindow, but that hides the whole centerView instead of just the SecondWindow.

Again, I am no expert, but I thought this was a bug and couldn't solve it myself. In case it helps I am testing on an Android device using 4.4.4 and SDK 4.0GA.

Thanks again

**Comment by manumaticx** [comment]
Thanks for this information.

Yeah, I also stumbled upon this. Maybe this method should be removed again as you've seen, there is no way to control this.

Let me explain what's going on here. Internally, the centerView is wrapped in a Fragment which you can add to the android backstack. Unfortunately, you cannot control the backstack on Titanium side. This leads to that exact problem: once you view is in on that backstack you can only remove it with the back button.

So, what I've done in one of my apps is the following (and I'd agree the demo app needs a little refactoring too). I've modified the global open method. Before opening a new controller it adds the id of the current controller to a backstack array. Now, whenever you switch the centerView by selecting an element in the menu we can go back to the previous view. To keep the memory clean, not the controller itself is hold in the backstack but only its id so we can close this, clean it up and just reopen it when we want to have it back. To implement this you'll need this functionality in your SDK: https://github.com/appcelerator/titanium_mobile/pull/6859

Since this is a very vague workaround for now, I don't really integrate this into the demo app although it works fine for me. But there's probably another solution you could go with. If you'd use a container view as your center view and add / remove content views to this instead of using replaceCenterView you could keep control of it.

**Comment by Yakito** [comment]
Thanks a lot, I will test your solution, I might ask you for some help in the future if I can't get it working, but I will give it a try first. Thanks again.
