### ISSUE TITLE
How to release memory?

### ISSUE THREAD

**Issue by DouglasHennrich** [manumaticx/Ti.DrawerLayout#37]
Hi! I have a question... how can I release memory from views when I attach them to my center view through replaceCenterView saving on backstack. There's a way to add a function on androidback button to remove all child from the current view before close it ?

I don't know why but my memory explode when I put a image as background of my view.

Thanks

**Comment by manumaticx** [comment]
Hi @DouglasHennrich 

as discussed [here](https://github.com/manumaticx/Ti.DrawerLayout/issues/34#issuecomment-108906157) I probably will remove the `replaceCenterView` method again or at least add some information in the docs about this problem. It's indeed a little hard to keep it clean since you cannot really control the backstack.
I'm planning to provide a best practice guide for second-level navigation within the drawers center view as soon as I have some time to waste.
