### ISSUE TITLE
CenterView scrolls back to top when going back

### ISSUE THREAD

**Issue by Velan** [manumaticx/Ti.DrawerLayout#46]
Hello!

I have an app that uses heavily ListViews and it often happens that I navigate from one ListView to another. I have an issue when and I navigate back to a ListView, the scroll position is not retained and the ListView appears in its initials position.

I do not have the issue with TableViews nor weirdly the first ListView that appears in the center when the Drawer is created, all subsequent ListViews that replace the first one have the issue though.

I also tried the 1.3.4 build, but that build deprecated the `replaceCenterView` method and made it identical to the `setCenterView`, and it's not possible to add views to the backstack anymore.

**Comment by manumaticx** [comment]
Hi @Velan 

Since 1.3.2 this module does not use Fragments anymore in favor of supporting MapView. So `replaceCenterView` was dropped too as the centerView is now based on Views (TiCompositeLayout) and it is not needed anymore (no Fragments, no backstack).

So now, if you call `setCenterView` there is no going back to the previous view. You could use a container view as the centerView and add / remove views to that using your own backstack. I do it like this but without keeping the references to views. I usually only keep the controller id and clean up the old view and initialize the new one because of memory reasons. If you want to see an example I could update the [demo app](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App) to use a backstack.

**Comment by Velan** [comment]
Hey @manumaticx 

Thanks a lot for the very quick reply!

The issue I have with using my own backstack is that I would not be able to put the scroll position back to the same position it was before replacing the view. That info is available for regular ScrollViews in Titanium but not TableViews or ListViews. I'd probably need a native helper module to get and set those infos.

**Comment by manumaticx** [comment]
Yes, that's indeed hard to accomplish. In native land you would use Fragments to solve this. The Fragment is able to resume to it's paused state like an activity. But I think there's also a Titanium issue with ListViews. I've seen this problem (loosing the scroll position) somewhere else.

I'm wondering if this also happens when you keep the ListView in memory (only remove it from parent and put it back later) when changing the centerView. But this could cause performance / memory problems.

**Comment by dpwilhelmsen** [comment]
@manumaticx I'd be interested in seeing an example of how you handle a backstack if you have one readily available. I appreciate all the work you put in maintaining this library.

**Comment by manumaticx** [comment]
@dpwilhelmsen hey, I've just updated the [demo app](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App) with my backstack implementation. Hope this helps! :)

**Comment by dpwilhelmsen** [comment]
Thanks! I appreciate it!

**Comment by manumaticx** [comment]
Closing this since there's probably no way to fix this in the module code

**Comment by Velan** [comment]
@manumaticx 

No problem !

I ended up implementing my own backstack with infos about the scroll position in a ListView (needed a native helper module for that). It's working fine now.

Thanks for your help!
