### ISSUE TITLE
Changing selected row when opening controller via API

### ISSUE THREAD

**Issue by Yakito** [manumaticx/Ti.DrawerLayout#50]
Hello! This is more a question than an issue, but I'v been trying to do it myself and couldn't find the way.

I am opening a controller from one of my views using the following code

    var searchWindow = Alloy.createController('search', args);
    Alloy.Globals.open(searchWindow);

This opens the controller fine but the selected item in the menu remains the same thus breaking my navigation.

Is there any way I can change the selected item in the menu for my `search` controller.

I guess it would be something like `$.menu.TableView.setRow` but I can't seem to understand how to call `$.menu` from another controller without getting `undefined`.

Any tip will be appreciated!
Thanks!

**Comment by manumaticx** [comment]
Assuming your code is based on the demo app and the `search` controller represents a menu item, you can do this by using this code (from any controller):

```js
Alloy.Globals.menu.select('search', function(){
    Alloy.Globals.optionsmenu();
});

// instead of 
/*
var searchWindow = Alloy.createController('search', args);
Alloy.Globals.open(searchWindow);
*/
```

**Comment by Yakito** [comment]
Hello Manuel, thanks a lot for your time. My code is indeed based on the demo app.

I am getting an undefined error when I try your code: 

    Cannot call method 'select' of undefined.

Where is `Alloy.Globals.menu` defined? Or should I define it somewhere? 

Thanks again for your time!

**Comment by manumaticx** [comment]
In the demo its defined in the index controller https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App/blob/master/app/controllers/index.js#L36

**Comment by Yakito** [comment]
Thanks again! I checked the code and it looks like I have an older version of the demo app so I will need to fix my code to have the menu inside a global variable.

Thanks a lot for your time (I might need to bother again in the future, but I will try to fix it myself)

**Comment by manumaticx** [comment]
Yeah, the app became a little complex. I've updated it a few weeks ago with a backstack implementation showing how to handle the back button. You can see all the changes in the commits. There's some more changes than making the menu global.

Please note that I've also updated the menu.select method to include a callback (allowing to update the options menu after the new controller is open) and the ability to open a controller by it's id (which must be defined in the menu view).

As you can see, the global back function uses the same method to open the previous controller since it's id was stored in the backstack array. 

Don't hesitate to ask. I'll try to help.

**Comment by Yakito** [comment]
Hello Manuel, maybe this is super easy for you to answer. I been modifying my code to make it work with the new changes and everything works fine except for one tiny thing.

When I use the code you sent me to select an item of the menu from a controller

    Alloy.Globals.menu.select('search', function(){
        Alloy.Globals.optionsmenu();
    });

I get the following error

    Cannot read property 'actionBar' of undefined

Inside the controller I have a function which I use to set the actionBar title and it works fine when I call it from the menu but fails when I call it directly. Here is the function

    function onCreateOptionsMenu(e) {
    	    if (e.actionBar) {
		    e.actionBar.title = "Add Place";
	    }

Do you have any idea what might be causing the error to happen only when I call the item directly from the controller?

Again, tons of thanks!

**Comment by manumaticx** [comment]
The `onCreateOptionsMenu` method should not be called directly. It's actually just a callback that you define that gets called by the system. In case of the demo code this method is just forwarded from the main window (or activity) to the nested controllers. This allows you to have separate optionmenus for each content view. 

You can force it to be called with `activity.invalidateOptionsMenu()` - this is used [here](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App/blob/master/app/controllers/menu.js#L79) since we want to remove items from the menu when the drawer opens etc.

 But if updating the title is the only thing you want to do in this method then you don't have to use the optionsMenu callback. There are other ways to access the actionbar, e.g. with `$.index.activity.actionBar` for a window or with `args.parent.activity.actionBar` for a nested controller like `main`. You could also use  [abx](https://github.com/ricardoalcocer/actionbarextras) ;)

I hope I didn't got you wrong and this was somehow helpful.

**Comment by Yakito** [comment]
Thanks again Manuel!
