### ISSUE TITLE
Styling Action Bar Issue

### ISSUE THREAD

**Issue by kshamsuddin** [manumaticx/Ti.DrawerLayout#54]
**Testing Environment:**
*Ti SDK: 5.1.1.GA
MAC OSX 10.10.5
Target Android API: 23
Target Device: Android Genymotion Emulator*

Hi,
I'm very new to Titanium. I have been picking up a project where we used your module. I recently updated the module to version 1.3.6 and tested with Ti SDK 5.1.1.GA. Everything seems to be working fine except the actionbar styling. The styling is not working and the actionbar home icon disappeared.

We used [actionbar style generator](http://jgilfelt.github.io/android-actionbarstylegenerator/#name=cpl&compat=appcompat&theme=light&actionbarstyle=solid&texture=0&hairline=0&neutralPressed=1&backColor=f89925%2C100&secondaryColor=D6D6D6%2C100&tabColor=f89925%2C100&tertiaryColor=F2F2F2%2C100&accentColor=f89925%2C100&cabBackColor=FFFFFF%2C100&cabHighlightColor=f89925%2C100) which has been marked as deprecated.

Below is my tiapp.xml

	<android xmlns:android="http://schemas.android.com/apk/res/android">
	    <manifest android:versionCode="7" android:versionName="1.0.4">
	        <application android:theme="@style/Theme.Cpl"/>
	        <uses-sdk android:targetSdkVersion="23"/>
	    </manifest>
	</android>

Here is the styles_cpl.xml

<resources>

        <style name="Theme.Cpl" parent="@style/Theme.AppCompat.Light">
            <item name="android:actionBarItemBackground">@drawable/selectable_background_cpl</item>
            <item name="android:popupMenuStyle">@style/PopupMenu.Cpl</item>
            <item name="android:dropDownListViewStyle">@style/DropDownListView.Cpl</item>
            <item name="android:actionBarTabStyle">@style/ActionBarTabStyle.Cpl</item>
            <item name="android:actionDropDownStyle">@style/DropDownNav.Cpl</item>
            <item name="android:actionBarStyle">@style/ActionBar.Solid.Cpl</item>
            <item name="android:actionModeBackground">@drawable/cab_background_top_cpl</item>
            <item name="android:actionModeSplitBackground">@drawable/cab_background_bottom_cpl</item>
            <item name="android:actionModeCloseButtonStyle">@style/ActionButton.CloseMode.Cpl</item>
            
            
        </style>

        <style name="ActionBar.Solid.Cpl" parent="@style/Widget.AppCompat.Light.ActionBar.Solid.Inverse">
            <item name="android:background">@drawable/ab_solid_cpl</item>
            <item name="android:backgroundStacked">@drawable/ab_stacked_solid_cpl</item>
            <item name="android:backgroundSplit">@drawable/ab_bottom_solid_cpl</item>
            <item name="android:progressBarStyle">@style/ProgressBar.Cpl</item>
            <item name="android:icon">@drawable/actionicon</item>
        </style>

        <style name="ActionBar.Transparent.Cpl" parent="@style/Widget.AppCompat.Light.ActionBar">
            <item name="android:background">@drawable/ab_transparent_cpl</item>
            <item name="android:progressBarStyle">@style/ProgressBar.Cpl</item>
        </style>
        
        
        <style name="Theme.Cpl.Widget" parent="@style/Theme.AppCompat">
            <item name="android:popupMenuStyle">@style/PopupMenu.Cpl</item>
            <item name="android:dropDownListViewStyle">@style/DropDownListView.Cpl</item>
        </style>

    </resources>

Can anybody please advice what to modify to display a hexa value background color and app/home icon in the actionbar? 

Many thanks in advance for your time.

**Comment by manumaticx** [comment]
That generator is indeed deprecated and I encourage not using it anymore because it generates a lot of drawables which blows up your resources.

I recommend creating a fresh new Theme based on an AppCompat parent Theme. There's an excellent article from Ricardo Alocer: https://www.appcelerator.com/blog/2015/07/understanding-the-android-material-theme/

It explains the simple steps you need to configure to customize the AppComat parent Theme. For example, the property you are looking for is `<item name="colorPrimary">@color/primary</item>` - this sets the background of the Actionbar / Toolbar.

**Comment by kshamsuddin** [comment]
Many thanks. Would that bring the app/home icon on the action bar? 

Should I just remove all from platform/android/res/ first before creating a new theme?

**Comment by manumaticx** [comment]
The support for App Icon in Actionbar was dropped by Titanium since using it is not recommended anymore as per Material design guidelines. There's a workaround this as I answered [here](https://github.com/ricardoalcocer/actionbarextras/issues/92) (using the ABX module).

And yes, you can remove all the generated stuff from platform/android/res/ (but be careful to remove only the styles and drawables generated by the style generator and no resources that you have created).

**Comment by kshamsuddin** [comment]
Thanks for the help. Really appreciated.

**Comment by bmlyon** [comment]
Can someone please update the official documentation to say that the generator is deprecated? I spent hours trying this and it says to use the generator. Then I found this forum thread saying that it's deprecated.

http://docs.appcelerator.com/platform/latest/#!/guide/Android_Themes still says to use the theme generator.
