### ISSUE TITLE
android:paddingTop="24dp" is missing in the drawer_main.xml file of the module if downloaded from dist folder

### ISSUE THREAD

**Issue by prashantsaini1** [manumaticx/Ti.DrawerLayout#75]
Hi,

The issue I reported here on this module : **https://github.com/manumaticx/NavigationDrawer-Demo/issues/1** is the same I am going to put the solution for.

**_android:paddingTop="24dp"_** is missing in the **drawer_main.xml** file of the module if downloaded from dist folder.

If we use the module from the demo app modules folder, then padding line is present in **drawer_main.xml**

**Comment by manumaticx** [comment]
This is by design. You have to add the padding manually as stated [here](https://github.com/manumaticx/Ti.DrawerLayout/blob/master/documentation/index.md#tricks--pitfalls). The reason for this is that there are two ways of using the drawer depending on the Theme that is used. I decided to add no padding by default as it is easier to add by yourself if needed than removing it. (Either by adjusting the layout file as seen in the demo app or with `setToolbarPadding` in [ABX](https://github.com/ricardoalcocer/actionbarextras))

**Comment by prashantsaini1** [comment]
Thanks for clarifying all doubts and now it works as expected after following your advises.
